
config:
  profile: pst
  message: pst cloud config

Globals:
  DbType: mysql
  DriverClassName: net.sf.log4jdbc.DriverSpy
  Url: jdbc:log4jdbc:mysql://127.0.0.1:3306/pst
  UserName: com
  Password: com01

