# server name
config:
  message: egov39-sample message

# server port settings
server:
  port: 9023

# Overwrite the bins created from the Spring Framework 5.* - When you try to register bins with the same name - BeanDefinitionOverrideException occurs, setting that eliminates this.
spring:
  main:
    allow-bean-definition-overriding: true

# view settings - should exclude the dispatcher-servlet.xml setting
  mvc:
    view:
      prefix: /WEB-INF/jsp/egovframework/example/
      suffix: .jsp

# Thymeleaf settings
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    view-names: thymeleaf/*


